# Generated by Django 4.2 on 2023-05-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Suscripcion",
            fields=[
                ("id_suscripcion", models.AutoField(primary_key=True, serialize=False)),
                ("suscripcion", models.BooleanField()),
                ("usuario", models.CharField(max_length=40)),
            ],
        ),
    ]
